/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container': '#f0eee7',
        'on-surface-variant': '#414941',
        'on-primary-container': '#74ae7e',
        'surface-variant': '#e5e2db',
        'inverse-surface': '#31312c',
        'surface-container-low': '#f6f3ec',
        'tertiary-fixed': '#b1f1c5',
        'surface': '#fcf9f2',
        'tertiary': '#002915',
        'on-error-container': '#93000a',
        'surface-dim': '#dcdad3',
        'primary-fixed': '#b4f1bc',
        'tertiary-fixed-dim': '#96d4aa',
        'error': '#ba1a1a',
        'inverse-on-surface': '#f3f0e9',
        'surface-container-high': '#ebe8e1',
        'secondary-fixed': '#ffe088',
        'on-error': '#ffffff',
        'primary-container': '#01411c',
        'on-tertiary-container': '#71ae87',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#00210b',
        'surface-container-lowest': '#ffffff',
        'primary': '#00290f',
        'tertiary-container': '#004124',
        'inverse-primary': '#99d5a2',
        'secondary-container': '#fed65b',
        'secondary': '#735c00',
        'on-background': '#1c1c18',
        'outline-variant': '#c0c9be',
        'on-secondary-fixed': '#241a00',
        'surface-container-highest': '#e5e2db',
        'secondary-fixed-dim': '#e9c349',
        'primary-fixed-dim': '#99d5a2',
        'on-primary-fixed-variant': '#17512a',
        'background': '#fcf9f2',
        'surface-tint': '#326a40',
        'surface-bright': '#fcf9f2',
        'on-surface': '#1c1c18',
        'on-tertiary-fixed': '#002110',
        'on-secondary': '#ffffff',
        'on-secondary-fixed-variant': '#574500',
        'on-tertiary-fixed-variant': '#115131',
        'outline': '#717970',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#745c00',
        'error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '16px',
        gutter: '16px',
        xs: '4px',
        lg: '24px',
        'container-margin': '20px',
        sm: '8px',
        unit: '4px',
        xl: '40px',
      },
      fontFamily: {
        sans: ['Geist', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      keyframes: {
        'pulse-green': {
          '0%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(30,91,58,0.7)' },
          '70%': { transform: 'scale(1)', boxShadow: '0 0 0 10px rgba(30,91,58,0)' },
          '100%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(30,91,58,0)' },
        },
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'pulse-green': 'pulse-green 2s infinite',
        'fade-in': 'fadeIn 0.4s ease-out forwards',
      },
    },
  },
  plugins: [],
};
